Repository codestates-seb/seb45_pre_013, pull requests merged in 2023-08, with the labels that each got.

#35 Fe/feat/signup
  client/jsconfig.json
  client/src/App.jsx
  client/src/assets/image/earn.svg
  client/src/assets/image/minilogo.svg
  client/src/assets/image/save.svg
  client/src/assets/image/unlock.svg
  client/src/assets/image/unstruck.svg
  client/src/components/loginForm.jsx
  client/src/components/signupForm.jsx
  client/src/pages/login.jsx
  client/src/pages/signup.jsx
Labels: FE

#31 FE/Feat/question detail layout
  client/.eslintrc.cjs
  client/src/components/ArticleTitle.jsx
  client/src/components/QuestionDetail/AnswerArticle.jsx
  client/src/components/QuestionDetail/AnswerForm.jsx
  client/src/components/QuestionDetail/QuestionArticle.jsx
  client/src/components/QuestionDetail/Vote.jsx
  client/src/components/RightSidebar.jsx
  client/src/pages/QuestionDetail.jsx
  client/src/styles/global.jsx
Labels: FE

#56 [BE] 회원가입/로그인 기능 구현
  server/overflow/build.gradle
  server/overflow/src/main/java/com/preproject/overflow/member/auth/filter/JwtAuthenticationFilter.java
  server/overflow/src/main/java/com/preproject/overflow/member/auth/filter/JwtVerificationFilter.java
  server/overflow/src/main/java/com/preproject/overflow/member/auth/handler/MemberAccessDeniedHandler.java
  server/overflow/src/main/java/com/preproject/overflow/member/auth/handler/MemberAuthenticationEntryPoint.java
  server/overflow/src/main/java/com/preproject/overflow/member/auth/handler/MemberAuthenticationFailureHandler.java
  server/overflow/src/main/java/com/preproject/overflow/member/auth/handler/MemberAuthenticationSuccessHandler.java
  server/overflow/src/main/java/com/preproject/overflow/member/auth/jwt/JwtTokenizer.java
  server/overflow/src/main/java/com/preproject/overflow/member/confing/SecurityConfiguration.java
  server/overflow/src/main/java/com/preproject/overflow/member/controller/MemberController.java
  server/overflow/src/main/java/com/preproject/overflow/member/dto/LoginDto.java
  server/overflow/src/main/java/com/preproject/overflow/member/dto/MemberPatchDto.java
  server/overflow/src/main/java/com/preproject/overflow/member/dto/MemberPostDto.java
  server/overflow/src/main/java/com/preproject/overflow/member/dto/MemberResponseDto.java
  server/overflow/src/main/java/com/preproject/overflow/member/entity/Member.java
  server/overflow/src/main/java/com/preproject/overflow/member/exception/BusinessLogicException.java
  server/overflow/src/main/java/com/preproject/overflow/member/exception/ExceptionCode.java
  server/overflow/src/main/java/com/preproject/overflow/member/exception/advice/GlobalExceptionAdvice.java
  server/overflow/src/main/java/com/preproject/overflow/member/exception/response/ErrorResponse.java
  server/overflow/src/main/java/com/preproject/overflow/member/mapper/MemberMapper.java
  server/overflow/src/main/java/com/preproject/overflow/member/repository/MemberRepository.java
  server/overflow/src/main/java/com/preproject/overflow/member/service/MemberDetailsService.java
  server/overflow/src/main/java/com/preproject/overflow/member/service/MemberService.java
  server/overflow/src/main/java/com/preproject/overflow/member/utils/CustomAuthorityUtils.java
  server/overflow/src/main/java/com/preproject/overflow/member/utils/ErrorResponder.java
  server/overflow/src/main/java/com/preproject/overflow/member/utils/RandomNumberGenerator.java
  server/overflow/src/main/resources/application.yml
Labels: BE

#60 [feat] 질문기능구현
  .idea/.gitignore
  .idea/StackOverflow.iml
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  server/overflow/src/main/java/com/preproject/overflow/member/repository/MemberRepository.java
  server/overflow/src/main/java/com/preproject/overflow/question/controller/QuestionController.java
  server/overflow/src/main/java/com/preproject/overflow/question/dto/MultiResponseDto.java
  server/overflow/src/main/java/com/preproject/overflow/question/dto/PageInfo.java
  server/overflow/src/main/java/com/preproject/overflow/question/dto/QuestionPatchDto.java
  server/overflow/src/main/java/com/preproject/overflow/question/dto/QuestionPostDto.java
  server/overflow/src/main/java/com/preproject/overflow/question/dto/QuestionResponseDto.java
  server/overflow/src/main/java/com/preproject/overflow/question/dto/QuestionTagDto.java
  server/overflow/src/main/java/com/preproject/overflow/question/dto/QuestionTagResponseDto.java
  server/overflow/src/main/java/com/preproject/overflow/question/dto/QuestionVoteDto.java
  server/overflow/src/main/java/com/preproject/overflow/question/dto/SingleResponseDto.java
  server/overflow/src/main/java/com/preproject/overflow/question/entity/Question.java
  server/overflow/src/main/java/com/preproject/overflow/question/entity/QuestionTag.java
  server/overflow/src/main/java/com/preproject/overflow/question/exception/BusinessLogicException.java
  server/overflow/src/main/java/com/preproject/overflow/question/exception/ExceptionCode.java
  server/overflow/src/main/java/com/preproject/overflow/question/mapper/QuestionMapper.java
  server/overflow/src/main/java/com/preproject/overflow/question/repository/QuestionRepository.java
  server/overflow/src/main/java/com/preproject/overflow/question/repository/QuestionTagRepository.java
  server/overflow/src/main/java/com/preproject/overflow/question/service/QuestionService.java
  server/overflow/src/main/java/com/preproject/overflow/question/service/QuestionTagService.java
  server/overflow/src/main/java/com/preproject/overflow/tag/controller/TagController.java
  server/overflow/src/main/java/com/preproject/overflow/tag/dto/TagDto.java
  server/overflow/src/main/java/com/preproject/overflow/tag/entity/Tag.java
  server/overflow/src/main/java/com/preproject/overflow/tag/mapper/TagMapper.java
  server/overflow/src/main/java/com/preproject/overflow/tag/repository/TagRepository.java
  server/overflow/src/main/java/com/preproject/overflow/tag/service/TagService.java
Labels: BE

#61 [feat] 답변 기능 구현
  .idea/gradle.xml
  .idea/modules.xml
  .idea/modules/overflow.main.iml
  .idea/uiDesigner.xml
  server/overflow/src/main/java/com/preproject/overflow/answer/controller/AnswerController.java
  server/overflow/src/main/java/com/preproject/overflow/answer/dto/AnswerPatchDto.java
  server/overflow/src/main/java/com/preproject/overflow/answer/dto/AnswerPostDto.java
  server/overflow/src/main/java/com/preproject/overflow/answer/dto/AnswerResponseDto.java
  server/overflow/src/main/java/com/preproject/overflow/answer/dto/AnswerVotePatchDto.java
  server/overflow/src/main/java/com/preproject/overflow/answer/entity/Answer.java
  server/overflow/src/main/java/com/preproject/overflow/answer/mapper/AnswerMapper.java
  server/overflow/src/main/java/com/preproject/overflow/answer/repository/AnswerRepository.java
  server/overflow/src/main/java/com/preproject/overflow/answer/service/AnswerService.java
  server/overflow/src/main/java/com/preproject/overflow/member/exception/ExceptionCode.java
Labels: BE

#62 [feat] 응답값 닉네임 포함 가능하게 수정
  server/overflow/src/main/java/com/preproject/overflow/answer/controller/AnswerController.java
  server/overflow/src/main/java/com/preproject/overflow/answer/service/AnswerService.java
Labels: BE

#63 [BE-fix] Excetion 패키지 수정
  server/overflow/src/main/java/com/preproject/overflow/answer/service/AnswerService.java
  server/overflow/src/main/java/com/preproject/overflow/exception/BusinessLogicException.java
  server/overflow/src/main/java/com/preproject/overflow/exception/ExceptionCode.java
  server/overflow/src/main/java/com/preproject/overflow/exception/advice/GlobalExceptionAdvice.java
  server/overflow/src/main/java/com/preproject/overflow/exception/response/ErrorResponse.java
  server/overflow/src/main/java/com/preproject/overflow/member/service/MemberDetailsService.java
  server/overflow/src/main/java/com/preproject/overflow/member/service/MemberService.java
  server/overflow/src/main/java/com/preproject/overflow/member/utils/ErrorResponder.java
  server/overflow/src/main/resources/application.yml
Labels: BE

#64 [feat] 답변 생성 권한 확인 구현
  server/overflow/src/main/java/com/preproject/overflow/answer/controller/AnswerController.java
  server/overflow/src/main/java/com/preproject/overflow/answer/dto/AnswerPatchDto.java
  server/overflow/src/main/java/com/preproject/overflow/answer/dto/AnswerPostDto.java
  server/overflow/src/main/java/com/preproject/overflow/answer/service/AnswerService.java
  server/overflow/src/main/java/com/preproject/overflow/member/confing/SecurityConfiguration.java
Labels: BE

#65 [BE-feat] Question 기능 추가 구현
  server/overflow/src/main/java/com/preproject/overflow/question/controller/QuestionController.java
  server/overflow/src/main/java/com/preproject/overflow/question/dto/QuestionResponseDto.java
  server/overflow/src/main/java/com/preproject/overflow/question/entity/Question.java
  server/overflow/src/main/java/com/preproject/overflow/question/mapper/QuestionMapper.java
Labels: BE

#67 [feat] question 기능구현
  server/overflow/src/main/java/com/preproject/overflow/exception/ExceptionCode.java
  server/overflow/src/main/java/com/preproject/overflow/member/confing/SecurityConfiguration.java
  server/overflow/src/main/java/com/preproject/overflow/member/mapper/MemberMapper.java
  server/overflow/src/main/java/com/preproject/overflow/question/controller/QuestionController.java
  server/overflow/src/main/java/com/preproject/overflow/question/dto/QuestionResponseDto.java
  server/overflow/src/main/java/com/preproject/overflow/question/exception/BusinessLogicException.java
  server/overflow/src/main/java/com/preproject/overflow/question/exception/ExceptionCode.java
  server/overflow/src/main/java/com/preproject/overflow/question/service/QuestionService.java
Labels: BE

#70 [feat] 답변 생성 시 AnswerCount 올라가도록 구현
  server/overflow/src/main/java/com/preproject/overflow/answer/service/AnswerService.java
Labels: BE

#73 [feat] 답변 삭제 시 AnswerCount 내려가도록 구현
  server/overflow/src/main/java/com/preproject/overflow/answer/service/AnswerService.java
Labels: BE

#81 [feat] questionTag기능 삭제
  .idea/compiler.xml
  server/overflow/src/main/java/com/preproject/overflow/question/controller/QuestionController.java
  server/overflow/src/main/java/com/preproject/overflow/question/dto/QuestionPatchDto.java
  server/overflow/src/main/java/com/preproject/overflow/question/dto/QuestionPostDto.java
  server/overflow/src/main/java/com/preproject/overflow/question/dto/QuestionResponseDto.java
  server/overflow/src/main/java/com/preproject/overflow/question/dto/QuestionTagDto.java
  server/overflow/src/main/java/com/preproject/overflow/question/dto/QuestionTagResponseDto.java
  server/overflow/src/main/java/com/preproject/overflow/question/entity/Question.java
  server/overflow/src/main/java/com/preproject/overflow/question/entity/QuestionTag.java
  server/overflow/src/main/java/com/preproject/overflow/question/mapper/QuestionMapper.java
  server/overflow/src/main/java/com/preproject/overflow/question/repository/QuestionTagRepository.java
  server/overflow/src/main/java/com/preproject/overflow/question/service/QuestionService.java
  server/overflow/src/main/java/com/preproject/overflow/question/service/QuestionTagService.java
  server/overflow/src/main/java/com/preproject/overflow/tag/controller/TagController.java
  server/overflow/src/main/java/com/preproject/overflow/tag/dto/TagDto.java
  server/overflow/src/main/java/com/preproject/overflow/tag/entity/Tag.java
  server/overflow/src/main/java/com/preproject/overflow/tag/mapper/TagMapper.java
  server/overflow/src/main/java/com/preproject/overflow/tag/repository/TagRepository.java
  server/overflow/src/main/java/com/preproject/overflow/tag/service/TagService.java
Labels: BE

#82 [BE-server] 배포 설정
  server/overflow/Dockerfile
  server/overflow/src/main/java/com/preproject/overflow/member/confing/SecurityConfiguration.java
  server/overflow/src/main/resources/application.yml
Labels: BE, Server

#84 [BE-Server] 데이터 베이스 설정
  server/overflow/src/main/resources/application.yml
Labels: BE, Server
